services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    restart: unless-stopped
    network_mode: host
    devices:
      - /dev/video0:/dev/video0
    volumes:
      - ./intelmedia.yml:/mediamtx.yml
