[General]
TcpServerPort=0
MavlinkDialect=ardupilotmega

[UartEndpoint FC]
Device=/dev/ttyACM0
Baud=57600

[UdpEndpoint Laptop]
Mode=Normal
Address=100.106.38.39
Port=14550

# Justin's Tailscale IP
[UdpEndpoint Justin]
Mode=Normal
Address=100.91.210.67
Port=14550

# Ground station
[UdpEndpoint GroundStation]
Mode=Normal
Address=100.92.248.58
Port=14550

#To SEME
[UdpEndpoint SEME]
Mode=Normal
Address=100.106.38.39
Port=14550