#This main.conf file is used for mavlink_router 
[General]
TcpServerPort=0
MavlinkDialect=ardupilotmega

[UartEndpoint FC]
Device=/dev/ttyACM0
Baud=57600

# To SEME DON'T change this unless they change their ip
[UdpEndpoint SEME]
Mode=Normal
Address=100.106.38.39
Port=14550

# As a side note, limit the amount of connections to reduce bottleneck of output
# Server to be used as gateway
[UdpEndpoint Server]
Mode=Normal
Address=100.66.169.113
Port=14550

# Ground station for Mission Planner
[UdpEndpoint MissionPlannerGCS]
Mode=Normal
Address=100.92.248.58
Port=14550